### ISSUE TITLE
Feat: 온보딩 화면 및 회원가입 구현 (회원가입)

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/all-for-lesson#1]
##  📌 Overview
- 온보딩/회원가입 화면을 구현합니다.
- ~~예상 작업 시간 : 3h~~ 이틀이 꼬박 걸렸어요.......

<br />

## ✔️ Todo
- [x] 온보딩 화면 구현
  - [x] 수강생 버전
  - [x] 선생님 버전
- [x] 회원가입 기능 연결
  - [x] PhoneNum - Email - Password - Nickname 순서로 진행 (생년월일은 사용하지 않음)
  - [x] PhoneNum 필드를 수강생/선생님 구분용으로 활용
  - [x] 선생님으로 가입 시 Nickname은 실명으로 가입
- [x] 가입 완료 시
  - [x] UserDefaults - 액세스 토큰/리프레시 토큰 저장
  - [x] 홈 화면 연결
- [x] 로그인 화면 연결 (이미 계정이 있는 경우 대비)
- [x] 첫 화면 핸들링
