### ISSUE TITLE
Feat: 해시태그 검색 화면 구현

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/all-for-lesson#7]
##  📌 Overview
- 해시태그 검색 화면을 구현합니다.

<br />

## ✔️ Todo
- [x] 화면 진입 시마다 추천 해시태그 랜덤 데이터 바인딩
- [x] 검색어 입력 시 추천 해시태그 관련 데이터 바인딩
- [x] 검색 버튼 클릭 시 해시태그 검색 결과 화면 연결
- [ ] 추천 해시태그 버튼 클릭 시 검색 결과 화면 연결

<br />

## 🔗 References
- [[iOS/Swift] TabMan 라이브러리 사용하기 - (Custom tabbar / 상단 탭바 / 커스텀 탭바)](https://vanillacreamdonut.tistory.com/259)
- [RxSwift) RxCocoa - UICollectionView
출처: https://huniroom.tistory.com/entry/RxSwift-RxCocoa-UICollectionView [Tunko Development Diary:티스토리]](https://huniroom.tistory.com/entry/RxSwift-RxCocoa-UICollectionView)

<br />

### (1) 추천 해시태그 컬렉션뷰 버튼 클릭 시 이벤트가 발생하지 않는 이슈
- Button isUserInteractionEnabled = false
