### ISSUE TITLE
Feat: 레슨 결제 기능 연결

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/all-for-lesson#9]
##  📌 Overview
- 레슨 결제 기능을 구현합니다.

<br />

## ✔️ Todo
- [x] 결제 기능 연결
- [x] 결제 영수증 검증 API 연결
- [x] 기존 좋아요한 레슨 목록 -> 결제한 레슨으로 데이터 변경

<br />

## 🔗 References

<br />

### iamport-ios, Then 패키지 충돌 오류

- iamport-ios 패키지 디펜던시 내부에서 사용하는 Then 패키지와 직접 설치한 Then 패키지의 버전이 달라 발생하는 오류로 추정
- iamport-ios에서 의존하는 Then 라이브러리는 버전 2.7.0
- 내가 직접 설치한 Then 라이브러리는 버전 3.0 이상이기 때문에 서로 충돌
- 직접 설치한 라이브러리를 삭제하고 사용 

![스크린샷 2024-09-01 오전 12 11 19](https://github.com/user-attachments/assets/86082495-4b65-4b3f-af34-047fa0604ab8)

```swift
dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/ReactiveX/RxSwift.git", .upToNextMajor(from: "6.0.0")),
        .package(name: "RxBusForPort", url: "https://github.com/iamport/RxBus-Swift", .upToNextMinor(from: "1.3.0")),
        .package(url: "https://github.com/Alamofire/Alamofire.git", .upToNextMajor(from: "5.4.0")),
        .package(url: "https://github.com/devxoul/Then.git", .upToNextMajor(from: "2.7.0")),
        .package(url: "https://github.com/nicklockwood/SwiftFormat", from: "0.50.4")
    ],
```
